CREATE TABLE `t_mall_order_valuation_dealer` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VERSON` int(11) DEFAULT NULL COMMENT '版本号 ',
  `ORDERID` int(11) DEFAULT NULL COMMENT '订单ID ',
  `DEALERID` int(11) DEFAULT NULL COMMENT '经销商ID',
  `SCORESINCERITY` int(2) DEFAULT NULL COMMENT '诚信评分',
  `SCOREATTITUDE` int(2) DEFAULT NULL COMMENT '服务态度评分',
  `SCOREQUALITY` int(2) DEFAULT NULL COMMENT '服务品质评分',
  `VALID` int(1) DEFAULT NULL COMMENT '有效性',
  `ISSHOW` int(1) DEFAULT NULL COMMENT '状态 1:显示 0:隐藏',
  `USERID` int(11) DEFAULT NULL COMMENT '购买用户ID ',
  `OPERATORID` int(11) DEFAULT NULL COMMENT '操作者ID',
  `OPERTYPE` int(2) DEFAULT NULL COMMENT '操作者类型 ',
  `CDATE` datetime NOT NULL COMMENT '创建时间 ',
  `UDATE` datetime NOT NULL COMMENT '修改时间 ',
  PRIMARY KEY (`ID`),
  KEY `IDX_DEALERID_VALID` (`DEALERID`,`ISSHOW`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=utf8 COMMENT='订单商家评价';
